### ISSUE TITLE
Legend becomes difficult to read when multiples lines of data

### ISSUE THREAD

**Issue by impcymru-sian-sweet** [impcymru/impcymru-chart-formatter#14]
What I did:
Reformat chart with any data

What happened:
Legend of data is displayed but difficult to read because this is overlapped

What should've happened:
Displayed in a way which is easy to read

![image](https://user-images.githubusercontent.com/122369656/212284510-28e69fb2-00cc-4cba-b632-b4e638d69c8d.png)

**Comment by impcymru-adam-watkins** [comment]
A tolerable workaround might be to always place the legend on the right. And remove the legend if there are more than two choices.

**Comment by impcymru-adam-watkins** [comment]
Imperfect, but good enough for now.
