### ISSUE TITLE
With weekly data, monthly data is automatically plotted 

### ISSUE THREAD

**Issue by ImpCymru-Jessica-Pang** [impcymru/impcymru-chart-formatter#23]
![image](https://github.com/impcymru/impcymru-chart-formatter/assets/111059051/982ae5cc-2d6f-420f-b19f-40ed0fde869c)

With weekly data, monthly data is automatically plotted which is not right

**Comment by ImpCymru-Jessica-Pang** [comment]
Is there anything for dates where you can set when to use full dates, when to use full months, when to use abb months and when to use years?

**Comment by ImpCymru-Jessica-Pang** [comment]
Is there anything for dates where you can set when to use full dates, when to use full months, when to use abb months and when to use years?

**Comment by impcymru-adam-watkins** [comment]
Struggling to reproduce. Is this just underlying Excel behaviour? If you change the major units of the x-axis to use months (or set it to text) then the chart formatter respects this.
